version: "3"

services:
  todolist-server:
    build: .cloud/docker
    image: todolist-backend
    depends_on:
      - mysql
      - mysql-test
    volumes:
      - ./:/var/www:cached

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-todolist
    volumes:
      - db-data:/var/lib/mysql:cached

  mysql-test:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/var/www/public:cached
    depends_on:
      - todolist-server

volumes:
  db-data:
