---
- name: Ensures todolist-backend dirs exist
  file:
    path: "{{ app_dir }}"
    state: directory

- name: Adding .env file
  template:
    src: ../templates/.env.j2
    dest: "{{ app_dir }}/.env"
