---
- name: add vagrant to the user groups docker and sudo
  user:
    name: vagrant
    groups: sudo,docker
    state: present

- name: Ensures todolist-backend dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: docker
  with_items:
    - /var/www/todolist-backend
    - /var/www/todolist-backend/storage

- name: Adding nginx file
  template:
    src: ../templates/nginx.conf.j2
    dest: /var/www/todolist-backend/nginx.conf
    owner: vagrant
    group: docker

- name: Adding .env file
  template:
    src: ../templates/.env.j2
    dest: /var/www/todolist-backend/.env
    owner: vagrant
    group: docker
