---
- name: Ensures todolist-backend dirs exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ app_dir }}"

- name: Adding .env file
  template:
    src: ../templates/.env.j2
    dest: "{{ app_dir }}/.env"
